import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    paddingTop: 50,
    paddingBottom: 40,
    paddingHorizontal: 20,
    backgroundColor: '#071511',
    alignItems: 'center',
    flexGrow: 1,
  },
  headerRight: {
    width: '100%',
    alignItems: 'flex-end',
    marginBottom: 10,
  },
  settingsIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1E2926',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#3B99FC',
    marginTop: 5,
  },
  titleBorder: {
    width: 180,
    height: 2,
    backgroundColor: '#00D66C',
    marginTop: 6,
    marginBottom: 12,
  },
  statusText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginBottom: 20,
  },
  onlineText: {
    color: '#00D66C',
    fontWeight: 'bold',
  },
  logoContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 2,
    borderColor: '#3B99FC',
    backgroundColor: '#0D201A',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  logoText: {
    fontSize: 50,
    color: '#3B99FC',
  },
  hintText: {
    color: '#888888',
    fontSize: 12,
    marginBottom: 20,
    textAlign: 'center',
  },
  input: {
    width: '100%',
    backgroundColor: '#11221D',
    borderWidth: 1,
    borderColor: '#3B99FC',
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#FFFFFF',
    fontSize: 14,
    marginBottom: 16,
  },
  buttonContainer: {
    width: '100%',
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 20,
  },
  switchCard: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#11221D',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 6,
    marginBottom: 16,
  },
  switchLabel: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
  },
  accessBadge: {
    borderWidth: 1,
    borderColor: '#3B99FC',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 6,
    marginBottom: 16,
    backgroundColor: '#0D201A',
  },
  accessBadgeAdmin: {
    borderColor: '#00D66C',
  },
  accessText: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  accessTextAdmin: {
    color: '#00D66C',
    fontWeight: 'bold',
  },
  elementCard: {
    width: '70%',
    backgroundColor: '#11221D',
    borderWidth: 1,
    borderColor: '#3B99FC',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 12,
  },
  elementText: {
    color: '#3B99FC',
    fontWeight: 'bold',
    fontSize: 16,
  },
  generatorSection: {
    width: '100%',
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#1E2926',
    alignItems: 'center',
  },
  sectionTitle: {
    color: '#3B99FC',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  passwordDisplay: {
    backgroundColor: '#11221D',
    borderColor: '#00D66C',
    borderWidth: 1,
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    width: '100%',
    marginTop: 10,
  },
  passwordText: {
    color: '#00D66C',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 2,
  },
});